### ISSUE TITLE
Добавить Тюрингию

### ISSUE THREAD

**Issue by san-smith** [san-smith/victoria-divine-wind-mod#144]
Добавить страну, отредактировать национальные провинции, технологии, партии и т.д.

**Comment by vlad198483** [comment]
Средневековый Эрфурт рос и богател благодаря расположению на стыке важнейших торговых дорог Германии в центре региона, специализировавшегося на производстве сырья для голубой краски. Этому в немалой степени способствовали местные купцы-евреи (хотя еврейская община сильно пострадала от погромов после прихода «чёрной смерти»). Горожане в XII веке окружили город каменными стенами и стали выплачивать архиепископу ежегодную мзду за освобождение от его власти, в середине XIII века получили магдебургские привилегии, а к 1279 г. наконец освободились от верховенства майнцских архиепископов, добившись статуса вольного имперского города. 

В XIV—XV вв. Эрфурт состоял в торговом союзе с Мюльхаузеном и Нордхаузеном, который в первой трети XV века присоединился к ганзейскому объединению городов. С 1331 г. местная ярмарка привлекала купцов из окрестных городов и регионов. В XIV-XV вв. Эрфурт — четвёртый по величине город Германии[5] с населением около 20 000 человек. Городской совет контролировал около сотни окрестных деревень и замков, а также городок Зёммерда. В XIV веке здесь открылся третий по счёту университет Германии, просуществовавший до 1817 года. 
https://ru.wikipedia.org/wiki/%D0%AD%D1%80%D1%84%D1%83%D1%80%D1%82
Про Эрфурт, он же в Тюрингии?

**Comment by vlad198483** [comment]
про университет:
Университет Эрфурта (1392) традиционно считался третьим по возрасту университетом Германии — после университетов Гейдельберга (1386) и Кёльна (1388). Впрочем, краеведы не прекращают попыток доказать, что Эрфуртский университет существовал уже в 1379 году (и, таким образом, является первым по времени возникновения университетом Германии). Среди его студентов был будущий религиозный реформатор Мартин Лютер.
