### ISSUE TITLE
Добавить Бурбон

### ISSUE THREAD

**Issue by san-smith** [san-smith/victoria-divine-wind-mod#18]
Добавить новую страну **Бурбонне,** отредактировать национальные провинции, технологии, партии и т.д.

**Comment by vlad198483** [comment]
@san-smith Может правильней будет Бурбонне?
Понимаю, что ты брал из Е3, просто поправил

**Comment by vlad198483** [comment]
> @san-smith Может правильней будет Бурбонне?

Хотя можно и так, и так говорить, но в файлах Е3 был Бурбонне, по этому я написал так.
