### ISSUE TITLE
Добавить Турцию

### ISSUE THREAD

**Issue by san-smith** [san-smith/victoria-divine-wind-mod#234]
Добавить страну, отредактировать национальные провинции, технологии, партии и т.д.

**Comment by vlad198483** [comment]
Дворец Эдирне (тур. Edirne Sarayı) также известен как Сарай-ы Джедид-и Амире (Новый дворец) (тур. Saray-ı Cedid-i Amire) — дворец османских султанов в Эдирне. После дворца Топкапы в Стамбуле был крупнейшим дворцом в империи. 


Павильон Джиханнюма
Джиханнюма являлся наиболее ярким строением комплекса. Он был построен в 1452 году при Фатихе и представлял собой семи-этажное здание. На верхнем этаже располагался бассейн[3]. Ныне павильон разрушен.
