### ISSUE TITLE
Добавить Кандар

### ISSUE THREAD

**Issue by san-smith** [san-smith/victoria-divine-wind-mod#235]
Добавить страну, отредактировать национальные провинции, технологии, партии и т.д.

**Comment by vlad198483** [comment]
Сухопутная армия, принадлежавшая княжеству, состояла из двадцати пяти тысяч кавалеристов и участвовала в кампаниях в Румелии и Анатолии вместе с османской. Важной военной силой Джандаридов был флот. У княжества была верфь в Синопе. Хотя нет точной информации о численности военного флота, но известно, что в Синопе был флот ещё во времена сельджуков и Чобаногулларов. Флот Джандаридов напал на генуэзскую Каффу в 1361 году. Корабль, построенный Измаил-беем, мог перевозить 900 тонн 
https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D0%BE%D0%B3%D1%83%D0%BB%D0%BB%D0%B0%D1%80%D1%8B
